In [1]:
import pandas as pd

In [2]:
import os

os.getcwd()

'c:\\Users\\felip\\OneDrive\\Documentos\\3-semestre\\sprint-2024-2-portifolio\\Backend\\utils'

In [3]:
turma = pd.read_excel("..\..\Data\Ata final de resultados.xlsx", skiprows=5)
ano = pd.read_excel("..\..\Data\Ata final de resultados.xlsx", skiprows=6)
tabela = pd.read_excel("..\..\Data\Ata final de resultados.xlsx", skiprows=10)

nome_turma = turma.columns[68]
ano_turma = ano.columns[68]
tabela.head()

# IGUAIS:
ciencias = ['Nº', 'Nome', '1º', '2º', '3º', '4º', 'SF', 'F', 'CA', '%']
geografia = ['Nº', 'Nome', '1º.1', '2º.1', '3º.1', '4º.1', 'SF.1', 'F', 'CA', '%']
historia = ['Nº', 'Nome', '1º.2', '2º.2', '3º.2', '4º.2', 'SF.2', 'F', 'CA', '%']
lingua_portuguesa = ['Nº', 'Nome', '1º.3', '2º.3','3º.3', '4º.3', 'SF.3', 'F', 'CA', '%']
matematica = ['Nº', 'Nome', '1º.4', '2º.4','3º.4', '4º.4', 'SF.4', 'F', 'CA', '%']

#DIFERENTES:
artes = ['Nº', 'Nome', '1º.5', '2º.5', '3º.5', '4º.5', 'SF.5', 'F.1', 'CA.1', '%.1']
ed_fisica = ['Nº', 'Nome', '1º.6', '2º.6', '3º.6', '4º.6', 'SF.6', 'F.2', 'CA.2', '%.2']
ingles = ['Nº', 'Nome', '1º.7','2º.7', '3º.7', '4º.7', 'SF.7', 'F.3', 'CA.3', '%.3']

#MAIS DIFERENTES:
laboratorio = ['Nº', 'Nome', 'F.4', 'CA.4','%.4']
sala_de_leiura = ['Nº', 'Nome', 'F.5', 'CA.5', '%.5']
I_educomunicacao_e_novas_linguagens_lingua_estrangeira = ['Nº', 'Nome', 'F.6', 'CA.6', '%.6']
I_educomunicacao_e_novas_linguagens_outras = ['Nº', 'Nome', 'F.7', 'CA.7', '%.7']
II_culturas_arte_e_memoria_academia_estudantil_letras = ['Nº', 'Nome', 'F.8', 'CA.8', '%.8']
II_culturas_arte_e_memoria_artesvisuais_arte_canto_danca_hiphop_musica_teatro = ['Nº', 'Nome', 'F.9', 'CA.9', '%.9']
II_culturas_arte_e_memoria_outras = ['Nº', 'Nome', 'F.10', 'CA.10', '%.10']
III_orientacao_de_estudos_brinquedos_e_brincadeiras = ['Nº', 'Nome', 'F.11', 'CA.11', '%.11']
III_orientacao_de_estudos_jogos_e_brincadeiras = ['Nº', 'Nome', 'F.12', 'CA.12', '%.12']
anual = ['Nº', 'Nome', 'F.13', 'CA.13', '%.13']

df_ciencias = tabela[ciencias]
df_geografia = tabela[geografia]
df_historia = tabela[historia]
df_lingua_portuguesa = tabela[lingua_portuguesa]
df_matematica = tabela[matematica]

# Diferentes
df_artes = tabela[artes]
df_ed_fisica = tabela[ed_fisica]
df_ingles = tabela[ingles]

# Mais diferentes
df_laboratorio = tabela[laboratorio]
df_sala_de_leitura = tabela[sala_de_leiura]
df_I_educomunicacao_e_novas_linguagens_lingua_estrangeira = tabela[I_educomunicacao_e_novas_linguagens_lingua_estrangeira]
df_I_educomunicacao_e_novas_linguagens_outras = tabela[I_educomunicacao_e_novas_linguagens_outras]
df_II_culturas_arte_e_memoria_academia_estudantil_letras = tabela[II_culturas_arte_e_memoria_academia_estudantil_letras]
df_II_culturas_arte_e_memoria_artesvisuais_arte_canto_danca_hiphop_musica_teatro = tabela[II_culturas_arte_e_memoria_artesvisuais_arte_canto_danca_hiphop_musica_teatro]
df_II_culturas_arte_e_memoria_outras = tabela[II_culturas_arte_e_memoria_outras]
df_III_orientacao_de_estudos_brinquedos_e_brincadeiras = tabela[III_orientacao_de_estudos_brinquedos_e_brincadeiras]
df_III_orientacao_de_estudos_jogos_e_brincadeiras = tabela[III_orientacao_de_estudos_jogos_e_brincadeiras]
df_anual = tabela[anual]

df_anual.head()

   Nº                               Nome   F.13  CA.13   %.13
0   1             AGATHA DE JESUS SANTOS   21.0    0.0  95.00
1   2  ANA CLARA COSTA DE ABREU TANIMURA  156.0   35.0  71.19
2   3               ANDRE VALDO DE SOUZA   15.0    0.0  96.43
3   0     APARECIDA LAYSSA ARAUJO MORAES    NaN    NaN    NaN
4   4        ARTHUR MIGUEL PORTE PEREIRA  122.0    0.0  70.95

In [4]:
materias = [
    "ciencias",
    "geografia",
    "historia",
    "lingua_portuguesa",
    "matematica",
    "artes",
    "ed_fisica",
    "ingles",
    "laboratorio",
    "sala_de_leiura",
    "I_educomunicacao_e_novas_linguagens_lingua_estrangeira",
    "I_educomunicacao_e_novas_linguagens_outras",
    "II_culturas_arte_e_memoria_academia_estudantil_letras",
    "II_culturas_arte_e_memoria_artesvisuais_arte_canto_danca_hiphop_musica_teatro",
    "II_culturas_arte_e_memoria_outras",
    "III_orientacao_de_estudos_brinquedos_e_brincadeiras",
    "III_orientacao_de_estudos_jogos_e_brincadeiras",
    "anual"
]

dataframes = [
    df_ciencias,
    df_geografia,
    df_historia,
    df_lingua_portuguesa,
    df_matematica,
    df_artes,
    df_ed_fisica,
    df_ingles,
    df_laboratorio,
    df_sala_de_leitura,
    df_I_educomunicacao_e_novas_linguagens_lingua_estrangeira,
    df_I_educomunicacao_e_novas_linguagens_outras,
    df_II_culturas_arte_e_memoria_academia_estudantil_letras,
    df_II_culturas_arte_e_memoria_artesvisuais_arte_canto_danca_hiphop_musica_teatro,
    df_II_culturas_arte_e_memoria_outras,
    df_III_orientacao_de_estudos_brinquedos_e_brincadeiras,
    df_III_orientacao_de_estudos_jogos_e_brincadeiras,
    df_anual
]

In [5]:
json = {}
alunos = df_matematica['Nome'].tolist()
for nome, df in zip(materias, dataframes):
    json[nome] = df.to_dict(orient='records')
json['matematica']
len(alunos)

39

In [32]:
df = turma = pd.read_excel("..\..\Data\ALUNOS 1ªA.xlsx", skiprows=1)

df.head()

,Código,RA Prodesp,Código INEP,Nº,Nome do Aluno,Filiação 1,Data Nascimento
0,7056411,000120694901-6/SP,1.833813e+11,1,AGATHA DE JESUS SANTOS,DANIELA DE JESUS BATISTA,2017-12-11
1,7589735,000121630414-2/SP,1.859474e+11,2,ANA CLARA COSTA DE ABREU TANIMURA,MAYARA DE ABREU TANIMURA,2018-01-25
2,6953301,000120664237-3/SP,1.785586e+11,3,ANDRE VALDO DE SOUZA,CLETIANA ALVES DE SOUZA,2017-05-18
3,7043376,000120584200-7/SP,1.785485e+11,4,ARTHUR MIGUEL PORTE PEREIRA,PAMELA PALOMA DE SOUZA PORTE PEREIRA,2017-05-25
4,7367758,000122250704-3/SP,1.859490e+11,5,BRAYAN LUCCA FRANKLIN DOS SANTOS,DANIELA LEOPOLDINO DOS SANTOS,2017-09-02

In [ ]:
df = turma = pd.read_excel("..\..\Data\ALUNOS 1ªA.xlsx", skiprows=1)
alunos_lista = []

# Percorrendo cada linha do DataFrame
for _, row in df.iterrows():
    # Convertendo a data para o formato 'YYYY/MM/DD', se não for nula
    data_nascimento = None
    if pd.notnull(row.get("Data Nascimento")):
        data_nascimento = row["Data Nascimento"].strftime('%Y/%m/%d')
    
    # Tratando o campo 'codigoInep' para remover casas decimais
    codigo_inep = row.get("Código INEP", None)
    if pd.notnull(codigo_inep):
        codigo_inep = int(float(codigo_inep))  # Convertendo para inteiro

    # Montando o dicionário do aluno com os campos necessários
    aluno = {
        "nome": str(row.get("Nome do Aluno", None)),
        "filiacao1": str(row.get("Filiação 1", None)),
        "filiacao2": None,  # Garantindo que valores padrão também sejam string
        "nomeSocialAluno": str(row.get("Nome do Aluno", None)),
        "nomeAfetivoAluno": str(row.get("Nome do Aluno", None)),
        "dataNascimento": str(data_nascimento),
        "cpf": None,  # Valor padrão convertido para string
        "rg": row.get("rg", None),
        "codigoAluno": str(row.get("Código", None)),
        "codigoInep": str(codigo_inep),  # Removendo casas decimais
        "turma": None # Valor padrão convertido para string
    }
    
    # Adicionando o dicionário à lista
    alunos_lista.append(aluno)

alunos_lista

[{'nome': 'AGATHA DE JESUS SANTOS',
  'filiacao1': 'DANIELA DE JESUS BATISTA',
  'filiacao2': 'None',
  'nomeSocialAluno': 'AGATHA DE JESUS SANTOS',
  'nomeAfetivoAluno': 'AGATHA DE JESUS SANTOS',
  'dataNascimento': '2017/12/11',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '7056411',
  'codigoInep': '183381280669',
  'turma': 'None'},
 {'nome': 'ANA CLARA COSTA DE ABREU TANIMURA',
  'filiacao1': 'MAYARA DE ABREU TANIMURA',
  'filiacao2': 'None',
  'nomeSocialAluno': 'ANA CLARA COSTA DE ABREU TANIMURA',
  'nomeAfetivoAluno': 'ANA CLARA COSTA DE ABREU TANIMURA',
  'dataNascimento': '2018/01/25',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '7589735',
  'codigoInep': '185947361697',
  'turma': 'None'},
 {'nome': 'ANDRE VALDO DE SOUZA',
  'filiacao1': 'CLETIANA ALVES DE SOUZA',
  'filiacao2': 'None',
  'nomeSocialAluno': 'ANDRE VALDO DE SOUZA',
  'nomeAfetivoAluno': 'ANDRE VALDO DE SOUZA',
  'dataNascimento': '2017/05/18',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '6953301',
  'codigoInep': '178558647762',
  'turma': 'None'},
 {'nome': 'ARTHUR MIGUEL PORTE PEREIRA',
  'filiacao1': 'PAMELA PALOMA DE SOUZA PORTE PEREIRA',
  'filiacao2': 'None',
  'nomeSocialAluno': 'ARTHUR MIGUEL PORTE PEREIRA',
  'nomeAfetivoAluno': 'ARTHUR MIGUEL PORTE PEREIRA',
  'dataNascimento': '2017/05/25',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '7043376',
  'codigoInep': '178548464304',
  'turma': 'None'},
 {'nome': 'BRAYAN LUCCA FRANKLIN DOS SANTOS',
  'filiacao1': 'DANIELA LEOPOLDINO DOS SANTOS',
  'filiacao2': 'None',
  'nomeSocialAluno': 'BRAYAN LUCCA FRANKLIN DOS SANTOS',
  'nomeAfetivoAluno': 'BRAYAN LUCCA FRANKLIN DOS SANTOS',
  'dataNascimento': '2017/09/02',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '7367758',
  'codigoInep': '185949021230',
  'turma': 'None'},
 {'nome': 'BRUNA MARTA MONTEIRO RODRIGUES',
  'filiacao1': 'FERNANDA ADRIELE MONTEIRO RODRIGUES',
  'filiacao2': 'None',
  'nomeSocialAluno': 'BRUNA MARTA MONTEIRO RODRIGUES',
  'nomeAfetivoAluno': 'BRUNA MARTA MONTEIRO RODRIGUES',
  'dataNascimento': '2017/07/14',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '7262215',
  'codigoInep': '183364891264',
  'turma': 'None'},
 {'nome': 'CALEBE DE MELO MORAIS',
  'filiacao1': 'IRACIRA DE MELO',
  'filiacao2': 'None',
  'nomeSocialAluno': 'CALEBE DE MELO MORAIS',
  'nomeAfetivoAluno': 'CALEBE DE MELO MORAIS',
  'dataNascimento': '2017/11/26',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '7262278',
  'codigoInep': '183381396373',
  'turma': 'None'},
 {'nome': 'CALEBE FEITOSA DE BARROS',
  'filiacao1': 'IVANA LEITE FEITOSA DE BARROS',
  'filiacao2': 'None',
  'nomeSocialAluno': 'CALEBE FEITOSA DE BARROS',
  'nomeAfetivoAluno': 'CALEBE FEITOSA DE BARROS',
  'dataNascimento': '2018/02/23',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '7564977',
  'codigoInep': '185949718185',
  'turma': 'None'},
 {'nome': 'DANIEL ALVES AMORIM',
  'filiacao1': 'MARIA DO ROSARIO ALVES DA MATA',
  'filiacao2': 'None',
  'nomeSocialAluno': 'DANIEL ALVES AMORIM',
  'nomeAfetivoAluno': 'DANIEL ALVES AMORIM',
  'dataNascimento': '2017/05/10',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '6919481',
  'codigoInep': '178558553946',
  'turma': 'None'},
 {'nome': 'EMANUELLY RIBEIRO DE SOUSA',
  'filiacao1': 'POLIANE RIBEIRO DA SILVA',
  'filiacao2': 'None',
  'nomeSocialAluno': 'EMANUELLY RIBEIRO DE SOUSA',
  'nomeAfetivoAluno': 'EMANUELLY RIBEIRO DE SOUSA',
  'dataNascimento': '2018/01/03',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '7260685',
  'codigoInep': '183364891000',
  'turma': 'None'},
 {'nome': 'ENZO GABRIEL DE CALDAS PADILHA',
  'filiacao1': 'JUSCELINI DE CALDAS HOMENA',
  'filiacao2': 'None',
  'nomeSocialAluno': 'ENZO GABRIEL DE CALDAS PADILHA',
  'nomeAfetivoAluno': 'ENZO GABRIEL DE CALDAS PADILHA',
  'dataNascimento': '2017/06/26',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '6913737',
  'codigoInep': '178558553431',
  'turma': 'None'},
 {'nome': 'GABRIELA SANTOS DE NOVAES',
  'filiacao1': 'BARBARA SANTOS SILVA',
  'filiacao2': 'None',
  'nomeSocialAluno': 'GABRIELA SANTOS DE NOVAES',
  'nomeAfetivoAluno': 'GABRIELA SANTOS DE NOVAES',
  'dataNascimento': '2017/07/10',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '6936505',
  'codigoInep': '178510533740',
  'turma': 'None'},
 {'nome': 'GUILHERME ENRIQUEZ ALVES',
  'filiacao1': 'IZABELLA DE OLIVEIRA ENRIQUEZ',
  'filiacao2': 'None',
  'nomeSocialAluno': 'GUILHERME ENRIQUEZ ALVES',
  'nomeAfetivoAluno': 'GUILHERME ENRIQUEZ ALVES',
  'dataNascimento': '2018/03/11',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '7372471',
  'codigoInep': '185950744968',
  'turma': 'None'},
 {'nome': 'GYOVANNA KANEYOSHI DO NASCIMENTO',
  'filiacao1': 'ELISANGELA DO NASCIMENTO RODRIGUES',
  'filiacao2': 'None',
  'nomeSocialAluno': 'GYOVANNA KANEYOSHI DO NASCIMENTO',
  'nomeAfetivoAluno': 'GYOVANNA KANEYOSHI DO NASCIMENTO',
  'dataNascimento': '2017/07/17',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '6942065',
  'codigoInep': '178557367600',
  'turma': 'None'},
 {'nome': 'HEITOR GRALHA SILVA',
  'filiacao1': 'MICHELE OLIVEIRA GRALHA',
  'filiacao2': 'None',
  'nomeSocialAluno': 'HEITOR GRALHA SILVA',
  'nomeAfetivoAluno': 'HEITOR GRALHA SILVA',
  'dataNascimento': '2017/06/07',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '7555729',
  'codigoInep': '203625969058',
  'turma': 'None'},
 {'nome': 'JOAO LUKAS MENDES SOUZA',
  'filiacao1': 'JUVENILDA ALVES DE SOUZA',
  'filiacao2': 'None',
  'nomeSocialAluno': 'JOAO LUKAS MENDES SOUZA',
  'nomeAfetivoAluno': 'JOAO LUKAS MENDES SOUZA',
  'dataNascimento': '2018/01/28',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '7570766',
  'codigoInep': '192751498360',
  'turma': 'None'},
 {'nome': 'KIMBERLLY EDUARDA MARTINS DA SILVA',
  'filiacao1': 'PAMELA OLIVEIRA ALVES MARTINS',
  'filiacao2': 'None',
  'nomeSocialAluno': 'KIMBERLLY EDUARDA MARTINS DA SILVA',
  'nomeAfetivoAluno': 'KIMBERLLY EDUARDA MARTINS DA SILVA',
  'dataNascimento': '2017/08/24',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '7179816',
  'codigoInep': '215622242124',
  'turma': 'None'},
 {'nome': 'LAURA TAVARES DA SILVA',
  'filiacao1': 'TATIANE FERREIRA DA SILVA',
  'filiacao2': 'None',
  'nomeSocialAluno': 'LAURA TAVARES DA SILVA',
  'nomeAfetivoAluno': 'LAURA TAVARES DA SILVA',
  'dataNascimento': '2017/04/01',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '7000877',
  'codigoInep': '183379766320',
  'turma': 'None'},
 {'nome': 'LORENA CARDOSO LOPES',
  'filiacao1': 'ZILMA DE JESUS CARDOSO',
  'filiacao2': 'None',
  'nomeSocialAluno': 'LORENA CARDOSO LOPES',
  'nomeAfetivoAluno': 'LORENA CARDOSO LOPES',
  'dataNascimento': '2018/01/19',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '7589574',
  'codigoInep': '185950415042',
  'turma': 'None'},
 {'nome': 'LORENNA DE SOUZA OLIVEIRA GOMES',
  'filiacao1': 'VIVIANE DE SOUZA LEITE',
  'filiacao2': 'None',
  'nomeSocialAluno': 'LORENNA DE SOUZA OLIVEIRA GOMES',
  'nomeAfetivoAluno': 'LORENNA DE SOUZA OLIVEIRA GOMES',
  'dataNascimento': '2017/08/21',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '7220273',
  'codigoInep': '183364890888',
  'turma': 'None'},
 {'nome': 'MARIA ALICE NUNES SILVA',
  'filiacao1': 'MARILIA MERCIA SILVA',
  'filiacao2': 'None',
  'nomeSocialAluno': 'MARIA ALICE NUNES SILVA',
  'nomeAfetivoAluno': 'MARIA ALICE NUNES SILVA',
  'dataNascimento': '2018/02/19',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '7236536',
  'codigoInep': '183383534005',
  'turma': 'None'},
 {'nome': 'MARIA BEATRIZ SOBRAL DOS SANTOS',
  'filiacao1': 'ALINE SOBRAL DOS SANTOS',
  'filiacao2': 'None',
  'nomeSocialAluno': 'MARIA BEATRIZ SOBRAL DOS SANTOS',
  'nomeAfetivoAluno': 'MARIA BEATRIZ SOBRAL DOS SANTOS',
  'dataNascimento': '2017/07/30',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '6982107',
  'codigoInep': '178557518233',
  'turma': 'None'},
 {'nome': 'MARIA HELLENA AFONSO DE ATAIDE',
  'filiacao1': 'ERICA JANE PEREIRA DE ATAIDE',
  'filiacao2': 'None',
  'nomeSocialAluno': 'MARIA HELLENA AFONSO DE ATAIDE',
  'nomeAfetivoAluno': 'MARIA HELLENA AFONSO DE ATAIDE',
  'dataNascimento': '2017/10/19',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '7092317',
  'codigoInep': '203625967519',
  'turma': 'None'},
 {'nome': 'MATHEUS INACIO SANTOS DA SILVA',
  'filiacao1': 'JACIANE VERAS DOS SANTOS',
  'filiacao2': 'None',
  'nomeSocialAluno': 'MATHEUS INACIO SANTOS DA SILVA',
  'nomeAfetivoAluno': 'MATHEUS INACIO SANTOS DA SILVA',
  'dataNascimento': '2018/01/10',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '7642045',
  'codigoInep': '192750769107',
  'turma': 'None'},
 {'nome': 'NICOLLAS GABRIEL APOLINARIO DE MENEZES',
  'filiacao1': 'DEBORA PEREIRA DE MENEZES',
  'filiacao2': 'None',
  'nomeSocialAluno': 'NICOLLAS GABRIEL APOLINARIO DE MENEZES',
  'nomeAfetivoAluno': 'NICOLLAS GABRIEL APOLINARIO DE MENEZES',
  'dataNascimento': '2017/11/14',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '7911582',
  'codigoInep': '193531666915',
  'turma': 'None'},
 {'nome': 'RAFAELLA DA SILVA BRITO LEAL',
  'filiacao1': 'VIVIANE DA SILVA BRITO LEAL',
  'filiacao2': 'None',
  'nomeSocialAluno': 'RAFAELLA DA SILVA BRITO LEAL',
  'nomeAfetivoAluno': 'RAFAELLA DA SILVA BRITO LEAL',
  'dataNascimento': '2017/10/23',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '7306151',
  'codigoInep': '183379562830',
  'turma': 'None'},
 {'nome': 'ROBERT MIGUEL MAGALHAES DOS SANTOS',
  'filiacao1': 'JENIFFER MAGALHAES DE SOUSA',
  'filiacao2': 'None',
  'nomeSocialAluno': 'ROBERT MIGUEL MAGALHAES DOS SANTOS',
  'nomeAfetivoAluno': 'ROBERT MIGUEL MAGALHAES DOS SANTOS',
  'dataNascimento': '2017/04/08',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '6873413',
  'codigoInep': '178558552036',
  'turma': 'None'},
 {'nome': 'SOPHIA BERNARDO PONTES',
  'filiacao1': 'EDUARDA BERNARDO DE SOUZA',
  'filiacao2': 'None',
  'nomeSocialAluno': 'SOPHIA BERNARDO PONTES',
  'nomeAfetivoAluno': 'SOPHIA BERNARDO PONTES',
  'dataNascimento': '2018/01/03',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '7069186',
  'codigoInep': '183365578659',
  'turma': 'None'},
 {'nome': 'VINICIUS JESUS DE OLIVEIRA',
  'filiacao1': 'MARIA DA CONCEICAO DE OLIVEIRA SOUZA',
  'filiacao2': 'None',
  'nomeSocialAluno': 'VINICIUS JESUS DE OLIVEIRA',
  'nomeAfetivoAluno': 'VINICIUS JESUS DE OLIVEIRA',
  'dataNascimento': '2017/07/17',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '6906044',
  'codigoInep': '178653163807',
  'turma': 'None'},
 {'nome': 'YASMIM VICTORIA BERTI DOS SANTOS',
  'filiacao1': 'GABRIELA BARBOZA BERTI',
  'filiacao2': 'None',
  'nomeSocialAluno': 'YASMIM VICTORIA BERTI DOS SANTOS',
  'nomeAfetivoAluno': 'YASMIM VICTORIA BERTI DOS SANTOS',
  'dataNascimento': '2018/02/13',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '8049324',
  'codigoInep': '183331078181',
  'turma': 'None'},
 {'nome': 'YSADORA PEREIRA GODOY',
  'filiacao1': 'FRANCISCA MARIA LIMA PEREIRA',
  'filiacao2': 'None',
  'nomeSocialAluno': 'YSADORA PEREIRA GODOY',
  'nomeAfetivoAluno': 'YSADORA PEREIRA GODOY',
  'dataNascimento': '2017/09/19',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '7019177',
  'codigoInep': '178548455577',
  'turma': 'None'},
 {'nome': 'VICTOR GABRIEL SANTOS',
  'filiacao1': 'LUCILENE DA SILVA SANTOS',
  'filiacao2': 'None',
  'nomeSocialAluno': 'VICTOR GABRIEL SANTOS',
  'nomeAfetivoAluno': 'VICTOR GABRIEL SANTOS',
  'dataNascimento': '2017/07/04',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '7172408',
  'codigoInep': '183365634664',
  'turma': 'None'},
 {'nome': 'JHOELYSMAR DANNIELYS GUTIERREZ TOVAR',
  'filiacao1': 'HEYLIMAR ALEXANDRA TOVAR GONZALEZ',
  'filiacao2': 'None',
  'nomeSocialAluno': 'JHOELYSMAR DANNIELYS GUTIERREZ TOVAR',
  'nomeAfetivoAluno': 'JHOELYSMAR DANNIELYS GUTIERREZ TOVAR',
  'dataNascimento': '2018/03/06',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '8505580',
  'codigoInep': 'nan',
  'turma': 'None'},
 {'nome': 'FRANCISCO OLIVEIRA DA SILVA',
  'filiacao1': 'ELEN ROSSI OLIVEIRA DA SILVA',
  'filiacao2': 'None',
  'nomeSocialAluno': 'FRANCISCO OLIVEIRA DA SILVA',
  'nomeAfetivoAluno': 'FRANCISCO OLIVEIRA DA SILVA',
  'dataNascimento': '2017/04/02',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '8511190',
  'codigoInep': 'nan',
  'turma': 'None'},
 {'nome': 'ELLOA JESUS DOS SANTOS',
  'filiacao1': 'SUELY MARIA DE JESUS',
  'filiacao2': 'None',
  'nomeSocialAluno': 'ELLOA JESUS DOS SANTOS',
  'nomeAfetivoAluno': 'ELLOA JESUS DOS SANTOS',
  'dataNascimento': '2017/07/25',
  'cpf': 'None',
  'rg': 'None',
  'codigoAluno': '7224527',
  'codigoInep': '183364896061',
  'turma': 'None'}]

In [27]:
df_eol = df['Nome do Aluno']
df_ata = df_ciencias["Nome"]
alunos_ata = [aluno for aluno in df_ata]
alunos_eol = [aluno for aluno in df_eol]

print(len(alunos_eol))
print()
print(len(alunos_ata))

for aluno in alunos_ata:
    if aluno not in alunos_eol:
        print(aluno)

35

39
APARECIDA LAYSSA ARAUJO MORAES
JOAO VICTOR CIPRIANO LOPES
MIGUEL SILVA GAMA
PIETRO PORTELA RODRIGUES